### ISSUE TITLE
Bitswap Want, Have

### ISSUE THREAD

**Issue by AIDXNZ** [ipfs-rust/libp2p-bitswap#1]
Is there a 'have' aspect to the ledger to see who has the blocks? 

How would you suppose the best strategy would be to reduce duplicate blocks?

**Comment by dvc94ch** [comment]
That would require some kind of coordination, as for example all could decide to delete a block at the same time because it's above a given threshold. It also needs nodes trusting each other as misreporting could break the goals of the network. I think there's an ipfs cluster protocol or something that might deal with such issues

**Comment by troublescooter** [comment]
Perhaps of interest is the following paper analysing the competitiveness of file migration algorithms [0], both with and without global knowledge of the distribution of files/blocks.

[0] https://www.sciencedirect.com/science/article/pii/S0890540103000555
