### ISSUE TITLE
make sure the maximum block size is handled correctly

### ISSUE THREAD

**Issue by dvc94ch** [ipfs-rust/libp2p-bitswap#5]

**Comment by scanlime** [comment]
I can tentatively report that it's working... i've been moving around a lot of max-sized blocks without much trouble. It does seem like the bitswap protocol gets "bunched up", where large lists of blocks all try to go out at once and some of them end up failing because of this. Not sure that's related to size though.

**Comment by dvc94ch** [comment]
I just wrote a test case for this. If you send a message that is larger than max buf size, it will just be dropped on the receiving end.
